# Generated by Django 3.2.19 on 2023-10-12 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_change', models.TextField(blank=True, verbose_name='Последнее действие')),
                ('view', models.BooleanField(default=True, help_text='Отметьте, если значение должно отображаться в списке выбора. Уберите эту отметку вместо удаления значения.', verbose_name='Отображение')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Состояние договора')),
            ],
            options={
                'verbose_name': 'состояние договора',
                'verbose_name_plural': 'состояния договора',
            },
        ),
        migrations.CreateModel(
            name='ControlPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_change', models.TextField(blank=True, verbose_name='Последнее действие')),
                ('view', models.BooleanField(default=True, help_text='Отметьте, если значение должно отображаться в списке выбора. Уберите эту отметку вместо удаления значения.', verbose_name='Отображение')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Контроль ВП на ценообразование')),
            ],
            options={
                'verbose_name': 'контроль цены',
                'verbose_name_plural': 'контроль цены',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_change', models.TextField(blank=True, verbose_name='Последнее действие')),
                ('view', models.BooleanField(default=True, help_text='Отметьте, если значение должно отображаться в списке выбора. Уберите эту отметку вместо удаления значения.', verbose_name='Отображение')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Ведомство')),
            ],
            options={
                'verbose_name': 'ведомство',
                'verbose_name_plural': 'ведомства',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_change', models.TextField(blank=True, verbose_name='Последнее действие')),
                ('view', models.BooleanField(default=True, help_text='Отметьте, если значение должно отображаться в списке выбора. Уберите эту отметку вместо удаления значения.', verbose_name='Отображение')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'подразделение',
                'verbose_name_plural': 'подразделения',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_change', models.TextField(blank=True, verbose_name='Последнее действие')),
                ('view', models.BooleanField(default=True, help_text='Отметьте, если значение должно отображаться в списке выбора. Уберите эту отметку вместо удаления значения.', verbose_name='Отображение')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Должность')),
                ('abbr', models.CharField(max_length=200, verbose_name='Должность сокращенно')),
            ],
            options={
                'verbose_name': 'должность',
                'verbose_name_plural': 'должности',
            },
        ),
        migrations.CreateModel(
            name='StageBeginName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_change', models.TextField(blank=True, verbose_name='Последнее действие')),
                ('view', models.BooleanField(default=True, help_text='Отметьте, если значение должно отображаться в списке выбора. Уберите эту отметку вместо удаления значения.', verbose_name='Отображение')),
                ('name', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Этап подготовки')),
                ('file', models.BooleanField(blank=True, default=False, verbose_name='наличие отчетного документа')),
            ],
            options={
                'verbose_name': 'наименование этапа подготовки',
                'verbose_name_plural': 'наименования этапов подготовки',
            },
        ),
        migrations.CreateModel(
            name='StageEndName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_change', models.TextField(blank=True, verbose_name='Последнее действие')),
                ('view', models.BooleanField(default=True, help_text='Отметьте, если значение должно отображаться в списке выбора. Уберите эту отметку вместо удаления значения.', verbose_name='Отображение')),
                ('name', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Этап завершения')),
                ('file', models.BooleanField(blank=True, default=False, verbose_name='наличие отчетного документа')),
            ],
            options={
                'verbose_name': 'наименование этапа завершения',
                'verbose_name_plural': 'наименования этапов завершения',
            },
        ),
        migrations.CreateModel(
            name='StageMiddleName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_change', models.TextField(blank=True, verbose_name='Последнее действие')),
                ('view', models.BooleanField(default=True, help_text='Отметьте, если значение должно отображаться в списке выбора. Уберите эту отметку вместо удаления значения.', verbose_name='Отображение')),
                ('name', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Этап выполнения')),
                ('file', models.BooleanField(blank=True, default=False, verbose_name='наличие отчетного документа')),
            ],
            options={
                'verbose_name': 'наименование этапа выполнения',
                'verbose_name_plural': 'наименования этапов выполнения',
            },
        ),
        migrations.CreateModel(
            name='StatusContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_change', models.TextField(blank=True, verbose_name='Последнее действие')),
                ('view', models.BooleanField(default=True, help_text='Отметьте, если значение должно отображаться в списке выбора. Уберите эту отметку вместо удаления значения.', verbose_name='Отображение')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Статус договора')),
            ],
            options={
                'verbose_name': 'статус договора',
                'verbose_name_plural': 'статусы договора',
            },
        ),
        migrations.CreateModel(
            name='SubDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_change', models.TextField(blank=True, verbose_name='Последнее действие')),
                ('view', models.BooleanField(default=True, help_text='Отметьте, если значение должно отображаться в списке выбора. Уберите эту отметку вместо удаления значения.', verbose_name='Отображение')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Субподразделение')),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='database.division', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'субподразделение',
                'verbose_name_plural': 'субподразделения',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_change', models.TextField(blank=True, verbose_name='Последнее действие')),
                ('view', models.BooleanField(default=True, help_text='Отметьте, если значение должно отображаться в списке выбора. Уберите эту отметку вместо удаления значения.', verbose_name='Отображение')),
                ('name', models.CharField(blank=True, db_index=True, max_length=150, verbose_name='Фамилия И.О.')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=150, verbose_name='Отчество')),
                ('tabel', models.PositiveIntegerField(blank=True, unique=True, verbose_name='табельный номер')),
                ('norma', models.CharField(blank=True, max_length=150, verbose_name='норма часов')),
                ('post_abbr', models.CharField(blank=True, max_length=150, verbose_name='Должность сокращенно')),
                ('getdoc', models.BooleanField(blank=True, default=False, verbose_name='Выдающий')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='database.division', verbose_name='Подразделение')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='database.post', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_change', models.TextField(blank=True, verbose_name='Последнее действие')),
                ('view', models.BooleanField(default=True, help_text='Отметьте, если значение должно отображаться в списке выбора. Уберите эту отметку вместо удаления значения.', verbose_name='Отображение')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Заказчик')),
                ('city', models.CharField(max_length=200, verbose_name='Город')),
                ('inn', models.IntegerField(blank=True, null=True, verbose_name='ИНН')),
                ('getdoc', models.BooleanField(blank=True, default=False, verbose_name='Выдающий')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='database.department', verbose_name='Ведомство')),
            ],
            options={
                'verbose_name': 'организация',
                'verbose_name_plural': 'организации',
            },
        ),
    ]
