# Generated by Django 3.2.19 on 2023-10-13 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
        ('contract', '0002_alter_member_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='employee',
            field=models.ForeignKey(blank=True, limit_choices_to={'view': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='database.employee', verbose_name='Сотрудник'),
        ),
    ]
